//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YahtzeeTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YahtzeeTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                              ---------
        ///                             | Score |
        ///                             ---------
        ///----------
        ///| Ones   |...................3
        ///----------
        ///----------
        ///| Twos   |...................6
        ///----------
        ///----------
        ///| Threes |...................9
        ///----------
        ///----------
        ///| Fours  |...................12
        ///----------
        ///----------
        ///| Fives  |...................15
        ///----------
        ///----------
        ///| Sixes  |...................18
        ///----------
        ///---------------
        ///| Total Score |..............63
        ///--- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CompletedScoreSheetConsoleOutput {
            get {
                return ResourceManager.GetString("CompletedScoreSheetConsoleOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                              ---------
        ///                             | Score |
        ///                             ---------
        ///----------
        ///| Ones   |...................
        ///----------
        ///----------
        ///| Twos   |...................
        ///----------
        ///----------
        ///| Threes |...................
        ///----------
        ///----------
        ///| Fours  |...................
        ///----------
        ///----------
        ///| Fives  |...................
        ///----------
        ///----------
        ///| Sixes  |...................
        ///----------
        ///---------------
        ///| Total Score |..............
        ///-------------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmptyScoreSheetConsoleOutput {
            get {
                return ResourceManager.GetString("EmptyScoreSheetConsoleOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                              ---------
        ///                             | Score |
        ///                             ---------
        ///----------
        ///| Ones   |...................3
        ///----------
        ///----------
        ///| Twos   |...................6
        ///----------
        ///----------
        ///| Threes |...................
        ///----------
        ///----------
        ///| Fours  |...................0
        ///----------
        ///----------
        ///| Fives  |...................15
        ///----------
        ///----------
        ///| Sixes  |...................
        ///----------
        ///---------------
        ///| Total Score |..............24
        ///------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PartiallyCompletedScoreSheetConsoleOutput {
            get {
                return ResourceManager.GetString("PartiallyCompletedScoreSheetConsoleOutput", resourceCulture);
            }
        }
    }
}
